<?php
// version = 2014-12-20
$search  =array(

/* go */
'type=brown',
'type=airline',
'type=airport',
'type=airport service',
'type=bus',
'type=car rental',
'type=car sharing',
'type=ferry',
'type=marina',
'type=port',
'type=public transport',
'type=shuttle bus service',
'type=subway',
'type=taxi',
'type=train',
'type=tram',

/* see */
'type=steelblue',
'type=aquarium',
'type=archaeological site',
'type=botanical garden',
'type=bridge',
'type=building',
'type=bunker',
'type=castle',
'type=cathedral',
'type=cave',
'type=cemetery',
'type=church',
'type=fort',
'type=gallery',
'type=garden',
'type=lake',
'type=landmark',
'type=memorial',
'type=mining museum',
'type=monastery',
'type=mosque',
'type=museum',
'type=nunnery',
'type=open air museum',
'type=opera house',
'type=pagoda',
'type=palace',
'type=park',
'type=plantation',
'type=pyramid',
'type=religious site',
'type=sight',
'type=stadium',
'type=stud',
'type=synagogue',
'type=temple',
'type=tower',
'type=town hall',
'type=waterfall',
'type=zoological garden',

/* do */
'type=grey',
'type=amusement park',
'type=ballooning',
'type=beach',
'type=bike rental',
'type=cinema',
'type=circus',
'type=cultural organization',
'type=dive center',
'type=dolphinarium',
'type=festival',
'type=golf',
'type=horsecar',
'type=massage',
'type=mountain',
'type=quad bike',
'type=spa',
'type=sport',
'type=summit',
'type=swimming pool',
'type=theater',
'type=theme park',

/* buy */
'type=teal',
'type=antiquarian',
'type=bakery',
'type=bank',
'type=bike shop',
'type=book seller',
'type=delicatessen',
'type=jewellery',
'type=mall',
'type=market',
'type=pastry shop',
'type=shop',
'type=sports shop',

/* eat */
'type=chocolate',
'type=cafe',
'type=ice cream parlor',
'type=restaurant',
'type=restaurant and bar',
'type=snack bar',

/* drink */
'type=black',
'type=bar',
'type=beer garden',
'type=club',
'type=discotheque',
'type=pub',

/* sleep */
'type=navy',
'type=appartment',
'type=alpine hut',
'type=bed and bike',
'type=boarding house',
'type=campsite',
'type=guest house',
'type=holiday flat',
'type=hostel',
'type=hotel',
'type=hotel garni',
'type=pension',
'type=youth hostel',

/* other */
'type=forstgreen',
'type=administration',
'type=clinic',
'type=college',
'type=company',
'type=consulate',
'type=cooking class',
'type=customs',
'type=dentistry',
'type=embassy',
'type=fire brigade',
'type=government',
'type=guide',
'type=hospital',
'type=internet café',
'type=kindergarten',
'type=laundry',
'type=library',
'type=nursery',
'type=office',
'type=organisation',
'type=pharmacy',
'type=phone',
'type=photo store',
'type=practice',
'type=police',
'type=post',
'type=relief organisation',
'type=school',
'type=shipping company',
'type=surgery',
'type=toilet',
'type=tour operator',
'type=tourism authority',
'type=tourist information',
'type=travel agency',
'type=university'

);



























// offset = + 200 
$replace =array(

/* go */
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',
'type=go',

/* see */
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',
'type=see',

/* do */
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',
'type=do',

/* buy */
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',
'type=buy',

/* eat */
'type=eat',
'type=eat',
'type=eat',
'type=eat',
'type=eat',
'type=eat',

/* drink */
'type=drink',
'type=drink',
'type=drink',
'type=drink',
'type=drink',
'type=drink',

/* sleep */
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',
'type=sleep',

/* other */
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other',
'type=other'

);
?>